### PR TITLE
No gemini

### PR DESCRIPTION
**Pull request by dannylamb**
**GitHub Issue**: Part of https://github.com/Islandora-Devops/isle-dc/pull/132

# What does this Pull Request do?

Delete Gemini.  Rewrites milliner to use code in crayfish-commons instead of calling out to Gemini.

# How should this be tested?

Test with https://github.com/Islandora-Devops/isle-dc/pull/132

# Interested parties
@Islandora/8-x-committers

### CODE REVIEW

**Comment by elizoller** [comment]
does this mean that no gemini = fedora 6?

**Comment by dannylamb** [comment]
@elizoller It's all jumbled up here.  But they're not strictly requiring one or the other.

**Comment by dannylamb** [comment]
Codecov is grumpy b/c deleting a whole microservice has upset the code coverage balance.  But other than that this is green.  Travis abides by all my updated tests.

**Comment by dannylamb** [comment]
@elizoller Took care of recast and its tests.  Took longer than I expected/wanted, but it's there!

**Comment by elizoller** [comment]
cool, i can give it another test 👍

**Comment by elizoller** [comment]
i've pulled the most recents down on this branch in crayfish and did a composer install inside recast
now i am testing recast service:
`curl -H"Authorization: Bearer islandora" -H"Accept: text/turtle" -H"Apix-Ldp-Resource: http://localhost:8080/fcrepo/rest/82/89/1a/3f/82891a3f-f23d-4561-95bd-9c4674c92695" http://localhost:8000/recast/`
returns
```
@prefix fedora: <http://fedora.info/definitions/v4/repository#> .
@prefix ldp: <http://www.w3.org/ns/ldp#> .
@prefix pcdm: <http://pcdm.org/models#> .
@prefix schema: <http://schema.org/> .
@prefix xsd: <http://www.w3.org/2001/XMLSchema#> .
@prefix ns0: <http://id.loc.gov/vocabulary/relators/> .
@prefix dc: <http://purl.org/dc/terms/> .

<http://localhost:8080/fcrepo/rest/82/89/1a/3f/82891a3f-f23d-4561-95bd-9c4674c92695>
  a fedora:Container, <http://purl.org/coar/resource_type/c_c513>, fedora:Resource, ldp:BasicContainer, pcdm:Object, ldp:RDFSource, ldp:Container ;
  fedora:lastModifiedBy "bypassAdmin" ;
  schema:dateModified "2021-03-05T21:26:09+00:00"^^xsd:dateTime ;
  schema:author <http://localhost:8000/user/1> ;
  ns0:prv <http://localhost:8000/taxonomy/term/37?_format=jsonld>, <http://localhost:8000/taxonomy/term/36?_format=jsonld> ;
  schema:sameAs <http://localhost:8000/node/12> ;
  schema:dateCreated "2021-03-05T21:16:19+00:00"^^xsd:dateTime ;
  ns0:pht <http://localhost:8000/taxonomy/term/35?_format=jsonld> ;
  dc:date "2018-01-01"^^xsd:date, "2018-01-01" ;
  dc:extent "1 item" ;
  fedora:createdBy "bypassAdmin" ;
  fedora:lastModified "2021-03-05T21:26:10.037Z"^^xsd:dateTime ;
  fedora:created "2021-03-05T21:16:21.666Z"^^xsd:dateTime ;
  dc:subject <http://localhost:8000/taxonomy/term/34>, <http://localhost:8000/taxonomy/term/33> ;
  pcdm:memberOf <http://localhost:8000/node/17> ;
  dc:description "A sign pointing towards a nail salon."@en ;
  dc:title "Nails Nails Nails"@en .
```

and `/add` returns the same thing as far as i can see:
curl -H"Authorization: Bearer islandora" -H"Accept: text/turtle" -H"Apix-Ldp-Resource//localhost:8080/fcrepo/rest/82/89/1a/3f/82891a3f-f23d-4561-95bd-9c4674c92695" http://localhost:8000/recast/add
```
@prefix fedora: <http://fedora.info/definitions/v4/repository#> .
@prefix ldp: <http://www.w3.org/ns/ldp#> .
@prefix pcdm: <http://pcdm.org/models#> .
@prefix schema: <http://schema.org/> .
@prefix xsd: <http://www.w3.org/2001/XMLSchema#> .
@prefix ns0: <http://id.loc.gov/vocabulary/relators/> .
@prefix dc: <http://purl.org/dc/terms/> .

<http://localhost:8080/fcrepo/rest/82/89/1a/3f/82891a3f-f23d-4561-95bd-9c4674c92695>
  a fedora:Container, <http://purl.org/coar/resource_type/c_c513>, fedora:Resource, ldp:BasicContainer, pcdm:Object, ldp:RDFSource, ldp:Container ;
  fedora:lastModifiedBy "bypassAdmin" ;
  schema:dateModified "2021-03-05T21:26:09+00:00"^^xsd:dateTime ;
  schema:author <http://localhost:8000/user/1> ;
  ns0:prv <http://localhost:8000/taxonomy/term/37?_format=jsonld>, <http://localhost:8000/taxonomy/term/36?_format=jsonld> ;
  schema:sameAs <http://localhost:8000/node/12> ;
  schema:dateCreated "2021-03-05T21:16:19+00:00"^^xsd:dateTime ;
  ns0:pht <http://localhost:8000/taxonomy/term/35?_format=jsonld> ;
  dc:date "2018-01-01"^^xsd:date, "2018-01-01" ;
  dc:extent "1 item" ;
  fedora:createdBy "bypassAdmin" ;
  fedora:lastModified "2021-03-05T21:26:10.037Z"^^xsd:dateTime ;
  fedora:created "2021-03-05T21:16:21.666Z"^^xsd:dateTime ;
  dc:subject <http://localhost:8000/taxonomy/term/34>, <http://localhost:8000/taxonomy/term/33> ;
  pcdm:memberOf <http://localhost:8000/node/17> ;
  dc:description "A sign pointing towards a nail salon."@en ;
  dc:title "Nails Nails Nails"@en .
  ```
  
 and same with replace
 
 am i missing a step somewhere?

**Comment by elizoller** [comment]
^ @dannylamb

**Comment by dannylamb** [comment]
I had to do some shenanigans to ensure things work on both http and https.  As a side effect, you have to configure the Drupal and Fedora base url's for Recast without a protocol.  Otherwise it won't make the match and you'll see what you're experiencing.

**Comment by elizoller** [comment]
in `/var/www/html/Crayfish/Recast/cfg/config.yaml` i changed it to:
```
fedora_resource:
  base_url: 127.0.0.1:8080/fcrepo/rest
gemini_base_url: http://127.0.0.1:8000/gemini
drupal_base_url: 127.0.0.1:8000
```
then i restarted apache just to be safe
then i reran curl commands to Recast as above and I'm still not getting the memberOf relationship transformed into a fedora URI, just getting the drupal URI

**Comment by dannylamb** [comment]
Crud... cuz that should do it.  When I get a moment to come up for air I'll take another look :crying_cat_face:

**Comment by dannylamb** [comment]
Ah yes, the old 'break the code to fix the tests'.... le sigh.

Oh well, at least I know what's going on now.  I can fix this and at least have ansible deploying it, too.

**Comment by elizoller** [comment]
👀

**Comment by elizoller** [comment]
pulled in this commit and did ran `curl -H"Authorization: Bearer islandora" -H"Accept: text/turtle" -H"Apix-Ldp-Resource: http://localhost:8080/fcrepo/rest/82/89/1a/3f/82891a3f-f23d-4561-95bd-9c4674c92695" http://localhost:8000/recast/add`

received this:
```
@prefix fedora: <http://fedora.info/definitions/v4/repository#> .
@prefix ldp: <http://www.w3.org/ns/ldp#> .
@prefix pcdm: <http://pcdm.org/models#> .
@prefix schema: <http://schema.org/> .
@prefix xsd: <http://www.w3.org/2001/XMLSchema#> .
@prefix ns0: <http://id.loc.gov/vocabulary/relators/> .
@prefix dc: <http://purl.org/dc/terms/> .

<http://localhost:8080/fcrepo/rest/82/89/1a/3f/82891a3f-f23d-4561-95bd-9c4674c92695>
  a fedora:Container, <http://purl.org/coar/resource_type/c_c513>, fedora:Resource, ldp:BasicContainer, pcdm:Object, ldp:RDFSource, ldp:Container ;
  fedora:lastModifiedBy "bypassAdmin" ;
  schema:dateModified "2021-03-05T21:26:09+00:00"^^xsd:dateTime ;
  schema:author <http://localhost:8000/user/1> ;
  ns0:prv <http://localhost:8000/taxonomy/term/37?_format=jsonld>, <http://localhost:8000/taxonomy/term/36?_format=jsonld> ;
  schema:sameAs <http://localhost:8000/node/12> ;
  schema:dateCreated "2021-03-05T21:16:19+00:00"^^xsd:dateTime ;
  ns0:pht <http://localhost:8000/taxonomy/term/35?_format=jsonld> ;
  dc:date "2018-01-01"^^xsd:date, "2018-01-01" ;
  dc:extent "1 item" ;
  fedora:createdBy "bypassAdmin" ;
  fedora:lastModified "2021-03-05T21:26:10.037Z"^^xsd:dateTime ;
  fedora:created "2021-03-05T21:16:21.666Z"^^xsd:dateTime ;
  dc:subject <http://localhost:8000/taxonomy/term/34>, <http://localhost:8000/taxonomy/term/33> ;
  pcdm:memberOf <http://localhost:8000/node/17> ;
  dc:description "A sign pointing towards a nail salon."@en ;
  dc:title "Nails Nails Nails"@en .
  ```
  
  

The recast log has:
```
[2021-03-11 12:59:28] app.INFO: Matched route "{route}". {"route":"GET_operation","route_parameters":{"_controller":"recast.controller:recast","operation":"add","_route":"GET_operation"},"request_uri":"http://localhost:8000/recast/add","method":"GET"} []
[2021-03-11 12:59:28] app.DEBUG: Checking for guard authentication credentials. {"firewall_key":"default","authenticators":1} []
[2021-03-11 12:59:28] app.DEBUG: Checking support on guard authenticator. {"firewall_key":"default","authenticator":"Islandora\\Crayfish\\Commons\\Syn\\JwtAuthenticator"} []
[2021-03-11 12:59:28] app.DEBUG: Calling getCredentials() on guard authenticator. {"firewall_key":"default","authenticator":"Islandora\\Crayfish\\Commons\\Syn\\JwtAuthenticator"} []
[2021-03-11 12:59:28] crayfish.syn.jwt_authentication.DEBUG: Token: islandora [] []
[2021-03-11 12:59:28] app.DEBUG: Passing guard token information to the GuardAuthenticationProvider {"firewall_key":"default","authenticator":"Islandora\\Crayfish\\Commons\\Syn\\JwtAuthenticator"} []
[2021-03-11 12:59:28] crayfish.syn.jwt_authentication.INFO: Logged in with static token: admin [] []
[2021-03-11 12:59:28] app.INFO: Guard authentication successful! {"token":"[object] (Symfony\\Component\\Security\\Guard\\Token\\PostAuthenticationGuardToken: PostAuthenticationGuardToken(user=\"admin\", authenticated=true, roles=\"admin\"))","authenticator":"Islandora\\Crayfish\\Commons\\Syn\\JwtAuthenticator"} []
[2021-03-11 12:59:28] app.DEBUG: Guard authenticator set no success response: request continues. {"authenticator":"Islandora\\Crayfish\\Commons\\Syn\\JwtAuthenticator"} []
[2021-03-11 12:59:28] app.DEBUG: Remember me skipped: it is not configured for the firewall. {"authenticator":"Islandora\\Crayfish\\Commons\\Syn\\JwtAuthenticator"} []
[2021-03-11 12:59:28] app.DEBUG: > GET /recast/add [] []
[2021-03-11 12:59:28] app.INFO: Request to add resource. [] []
[2021-03-11 12:59:28] app.DEBUG: Looking for reverse URI for: http://localhost:8080/fcrepo/rest/82/89/1a/3f/82891a3f-f23d-4561-95bd-9c4674c92695 [] []
[2021-03-11 12:59:28] app.DEBUG: is a Drupal URL [] []
[2021-03-11 12:59:28] app.DEBUG: Looking for reverse URI for: http://fedora.info/definitions/v4/repository#Container [] []
[2021-03-11 12:59:28] app.DEBUG: is a Drupal URL [] []
[2021-03-11 12:59:28] app.DEBUG: Looking for reverse URI for: http://purl.org/coar/resource_type/c_c513 [] []
[2021-03-11 12:59:28] app.DEBUG: is a Drupal URL [] []
[2021-03-11 12:59:28] app.DEBUG: Looking for reverse URI for: http://fedora.info/definitions/v4/repository#Resource [] []
[2021-03-11 12:59:28] app.DEBUG: is a Drupal URL [] []
[2021-03-11 12:59:28] app.DEBUG: Looking for reverse URI for: http://www.w3.org/ns/ldp#BasicContainer [] []
[2021-03-11 12:59:28] app.DEBUG: is a Drupal URL [] []
[2021-03-11 12:59:28] app.DEBUG: Looking for reverse URI for: http://pcdm.org/models#Object [] []
[2021-03-11 12:59:28] app.DEBUG: is a Drupal URL [] []
[2021-03-11 12:59:28] app.DEBUG: Looking for reverse URI for: http://localhost:8000/user/1 [] []
[2021-03-11 12:59:28] app.DEBUG: is a Drupal URL [] []
[2021-03-11 12:59:28] app.DEBUG: Looking for reverse URI for: http://localhost:8000/taxonomy/term/37?_format=jsonld [] []
[2021-03-11 12:59:28] app.DEBUG: is a Drupal URL [] []
[2021-03-11 12:59:28] app.DEBUG: Looking for reverse URI for: http://localhost:8000/taxonomy/term/36?_format=jsonld [] []
[2021-03-11 12:59:28] app.DEBUG: is a Drupal URL [] []
[2021-03-11 12:59:28] app.DEBUG: Looking for reverse URI for: http://localhost:8000/node/12 [] []
[2021-03-11 12:59:28] app.DEBUG: is a Drupal URL [] []
[2021-03-11 12:59:28] app.DEBUG: Looking for reverse URI for: http://localhost:8000/taxonomy/term/35?_format=jsonld [] []
[2021-03-11 12:59:28] app.DEBUG: is a Drupal URL [] []
[2021-03-11 12:59:28] app.DEBUG: Looking for reverse URI for: http://localhost:8000/taxonomy/term/34 [] []
[2021-03-11 12:59:28] app.DEBUG: is a Drupal URL [] []
[2021-03-11 12:59:28] app.DEBUG: Looking for reverse URI for: http://localhost:8000/taxonomy/term/33 [] []
[2021-03-11 12:59:28] app.DEBUG: is a Drupal URL [] []
[2021-03-11 12:59:28] app.DEBUG: Looking for reverse URI for: http://localhost:8000/node/17 [] []
[2021-03-11 12:59:28] app.DEBUG: is a Drupal URL [] []
[2021-03-11 12:59:28] app.DEBUG: Looking for reverse URI for: http://www.w3.org/ns/ldp#RDFSource [] []
[2021-03-11 12:59:28] app.DEBUG: is a Drupal URL [] []
[2021-03-11 12:59:28] app.DEBUG: Looking for reverse URI for: http://www.w3.org/ns/ldp#Container [] []
[2021-03-11 12:59:28] app.DEBUG: is a Drupal URL [] []
[2021-03-11 12:59:28] app.DEBUG: Adding acl -> http://www.w3.org/ns/auth/acl# [] []
[2021-03-11 12:59:28] app.DEBUG: Adding fedora -> http://fedora.info/definitions/v4/repository# [] []
[2021-03-11 12:59:28] app.DEBUG: Adding memento -> http://mementoweb.org/ns# [] []
[2021-03-11 12:59:28] app.DEBUG: Adding pcdm -> http://pcdm.org/models# [] []
[2021-03-11 12:59:28] app.DEBUG: Adding pcdmuse -> http://pcdm.org/use# [] []
[2021-03-11 12:59:28] app.DEBUG: Adding webac -> http://fedora.info/definitions/v4/webac# [] []
[2021-03-11 12:59:28] app.DEBUG: < 200 [] []
```

**Comment by elizoller** [comment]
Is that what i should be seeing, because I still don't see it working as how i'd expect it - seeing the fedora URi instead of the drupal URI for the member of?

**Comment by dannylamb** [comment]
Let me do another spin up of the playbook PR and make sure everything is as it should be.  Sry this is being such a pain to test.

**Review by elizoller — APPROVED** [review]
I was able to get recast working successfully with the playbook PR https://github.com/Islandora-Devops/islandora-playbook/pull/197

**Review by elizoller — APPROVED** [review]
I was able to get recast working successfully with the playbook PR https://github.com/Islandora-Devops/islandora-playbook/pull/197

**Comment by elizoller** [comment]
it'll need the branch of crayfish-commons changed back though https://github.com/Islandora/Crayfish/pull/111/files#diff-94360fcbfdaa0794f89079d0ed59a44bf07deb14fb01050e69055e595004cc8fR7

**Comment by dannylamb** [comment]
Composesr.json's have been reverted for both milliner and recast :+1:

**Comment by elizoller** [comment]
do the composer.locks need to be updated?

**Comment by dannylamb** [comment]
probably. i'll do that real quick.

**Comment by adam-vessey** [comment]
Just noticed... [`composer.phar` got committed here](https://github.com/Islandora/Crayfish/pull/111/files#diff-67ba8bffe9b4b295cfd4c5cd23d23edd02bf81febb63694af6c216db6f4741c0).

Suspecting it was accidental, but figuring it should be confirmed somewhere before throwing in a commit to remove it.

**Comment by dannylamb** [comment]
:man_facepalming: Oh noes.... that one's on me.

I'll make a PR to get rid of it.

**Pull request merged**
