### PR TITLE
Use crayfish commons

### PR DESCRIPTION
**Pull request by dannylamb**
**GitHub Issue**: Part of https://github.com/Islandora-CLAW/CLAW/issues/578

* Depends on https://github.com/Islandora-CLAW/Crayfish-Commons/pull/1

# What does this Pull Request do?

Adapts hypercube to use the param converter from Crayfish Commons, preparing it for use with API-X.

# What's new?

Using the param converter now, so the controller and its tests had to be touched up a little.

# How should this be tested?

- Get a JWT.  I added a dsm [here](https://github.com/Islandora-CLAW/islandora/blob/8.x-1.x/src/Plugin/RulesAction/Broadcaster.php#L122) and then performed a write operation on a FedoraResource to print it to the page.
- Use an HTTP client like Postman, making sure to add your token as an Authorization header for both of the following requests.
- Add a tiff to Fedora as a NonRdfSource at `http://localhost:8080/fcrepo/rest/some/crazy/path`
- Run the builtin webserver with `php -S localhost:8088 -t /path/to/Hypercube/src`
- Request the OCR for the tiff sending a GET request to Hypercube at `http://localhost:8088/some/crazy/path`

# Interested parties
Tag (@ mention) interested parties or, if unsure, @Islandora-CLAW/committers

### CODE REVIEW

**Comment by dannylamb** [comment]
This'll fail until https://github.com/Islandora-CLAW/Crayfish-Commons is on packagist.

**Comment by dannylamb** [comment]
@ruebot yes.  the resource must be in fedora at that point.  we'll use camel to ccontrol the order of operations so things get put into fedora before derivatives are attempted.

**Comment by jonathangreen** [comment]
Just tested this and it does what it says. I made a PR to your branch @dannylamb to add some documentation since I ran into some configuration issues when testing with Apache. 

Looks like travis is failing because the lock file needs to be update. Running `composer update` should fix it. Once Travis is happy I'm happy. 👍🏻

**Comment by jonathangreen** [comment]
IMO we should leave the lock in version control for the reasons listed here:
https://getcomposer.org/doc/01-basic-usage.md#commit-your-composer-lock-file-to-version-control

**Comment by dannylamb** [comment]
@jonathangreen++

**Comment by dannylamb** [comment]
I agree.  Keep the lockfile.

For some reason https://github.com/Islandora-CLAW/drupal-project was blowing up with its lockfile committed.  But I can't precisely recall why we're not using them in the individual d8 modules, so it probably is a good idea to revisit the issue @ruebot

**Comment by dannylamb** [comment]
Blergh.  Blocked by https://github.com/Islandora-CLAW/CLAW/issues/585.

**Comment by dannylamb** [comment]
Restarting the build to see what happen now that @jonathangreen has set everything up to share a line_endings check.

**Comment by dannylamb** [comment]
Looks like I gotta rebase for this to start passing. I can get to it tonight. On my phone right now.

**Comment by jonathangreen** [comment]
Looks like that previous fail was just a travis hiccup. Looks all good and working now.

**Pull request merged**
