### PR TITLE
Fix codecov reporting

### PR DESCRIPTION
**Pull request by jonathangreen**
## What does this Pull Request do?

We didn't have the correct settings in the PHP Unit XML so we weren't generating code coverage reports for the various microservices.

## What's new?

Should see codecov reported.

## How should this be tested?

Check that travis is able to send codecov reports.

## Interested parties
@Islandora-CLAW/committers

### CODE REVIEW

**Comment by whikloj** [comment]
👍

**Comment by whikloj** [comment]
@jonathangreen any idea on an easy way to add code coverage reports to the Drupal modules? Or is that not possible with the `run-tests.sh` script?

**Comment by jonathangreen** [comment]
@whikloj I'm not sure. I've been meaning to look into it one of these days. It would be really nice to get setup.

**Comment by whikloj** [comment]
I ran one by adding the SIMPLETEST args to the drupal/web/core/phpunit.xml.dist file and running phpunit directly. But that seems like a lot to setup. Maybe we need to provide a customized small phpunit.xml just for generating the code coverage.

**Pull request merged**
