### PR TITLE
Updating lock files for latest crayfish-commons changes

### PR DESCRIPTION
**Pull request by dannylamb**
Required for: https://github.com/Islandora-Devops/claw-playbook/pull/14

# What does this Pull Request do?

Updates the composer lockfile for each microservice.  Now we'll have the latest crayish-commons changes so we can deploy with Postrgres using Ansible.

# Interested parties
@jonathangreen

### CODE REVIEW

**Comment by jonathangreen** [comment]
@dannylamb looks like we have some PHP 5 version issues here...

**Comment by dannylamb** [comment]
@jonathangreen Gah, dangit... I'm gonna have to manually roll those back in the lockfile or figure out something more clever...

Or we just drop 5 and run away :grin:

**Comment by jonathangreen** [comment]
@dannylamb... its probably getting close to time to just 🔥burn 🔥 PHP 5 for CLAW and be done with it.

On the other hand, if you updated the lock files from a box with PHP 5 it would probably work for PHP 7, but I feel like this will continue to nag us for the next year until PHP 5 is officially dead.

**Comment by dannylamb** [comment]
@jonathangreen Or we just stop providing lockfiles? :man_shrugging: This is only going to get worse as 5 gets older, and really the lockfile on individual production systems are what people want.  We can't provide one for 7 if folks are going to run this for 5.

**Comment by jonathangreen** [comment]
@dannylamb I could be convinced that we should yank the lock files... just makes testing a bit more crazy, since we will never be totally sure what versions people are running...

Do you think a PHP5 lock file will work on PHP7? That might be the solution till we drop PHP5.

**Comment by dannylamb** [comment]
@jonathangreen Let's try the lockfile with 5 and see what happens.

Maybe we should press the issue about removing 5 early.  That's a big bullet we could dodge a year down the road.

**Comment by jonathangreen** [comment]
@dannylamb I'd be for it. I'm not sure anyone is CLAW-land would be opposed.

**Comment by jonathangreen** [comment]
🍾

**Comment by dannylamb** [comment]
For posterity, to install 5.6 and update the lock files on a fresh 16.04 environment, I did the following:
```bash
$ sudo apt-get install python-software-properties
$ sudo add-apt-repository ppa:ondrej/php
$ sudo apt-get update
$ sudo apt-get install -y php5.6
$ sudo apt-get install php5.6-dom
$ sudo apt-get install php5.6-mbstring
```
Then in each microservice, I installed a local copy of composer using php 5, which amounted to copy/pasting the composer install instructions and changing `php` to `php5.6`.  Your hash will vary from these instructions, so get the newest official instructions instead of blindly executing this:
```
$ sudo php5.6 -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
$ sudo php5.6 -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
$ sudo php5.6 -r "if (hash_file('SHA384', 'composer-setup.php') === '544e09ee996cdf60ece3804abc52599c22b1f40f4323403c44d44fdfdd586475ca9813a858088ffbc1f233e9b180f061') { echo 'Installer verified'; } else { echo 'Installer corrupt'; unlink('composer-setup.php'); } echo PHP_EOL;"
$ sudo php5.6 composer-setup.php
$ sudo php5.6 -r "unlink('composer-setup.php');"
```
Then I used 5.6 to run `composer update`:
```
$ sudo php5.6 composer.phar update
```

**Pull request merged**
