### PR TITLE
Configurable domain

### PR DESCRIPTION
**Pull request by dannylamb**
**GitHub Issue**: https://github.com/Islandora/documentation/issues/1664

# What does this Pull Request do?

These changes let you configure Gemini with drupal and fedora domains.  If you do not configure these values, behaviour is unchanged.

This is useful when you want to take data ingested in one environment to another, like a testing/staging server to production.  By configuring the `drupal_domain` and `fedora_domain` variables, you can force gemini to rewrite the urls on the way out so that they have the new domain.

# What's new?
Jams in two new config variables and makes `getUrls()` and `findByUri()` respect them.

# How should this be tested?

- Pull these changes in
- Copy/paste this chunk from `config.example.yml` to your `config.yaml` file
```
# Leave these blank unless you know what you're doing.  If you're moving
# data from one server to another and the domain changes, set these
# to your new domain.
fedora_domain:
drupal_domain:
```
- test gemini and confirm behaviour is the same.  i queried for a uuid, and then queried for the same item using `by_uri`
```
$ curl -s -H "Authorization: Bearer islandora" http://localhost:8000/gemini/02862b7c-0a80-45af-bc2a-690a007e40a0 | jq
{
  "drupal": "http://localhost:18000/_flysystem/fedora/islandora_3_TECHMD.xml",
  "fedora": "http://127.0.0.1:8080/fcrepo/rest/islandora_3_TECHMD.xml"
}

$ curl -I -H "X-Islandora-URI: http://localhost:18000/_flysystem/fedora/islandora_3_TECHMD.xml" -H "Authorization: Bearer islandora" http://localhost:8000/gemini/by_uri
HTTP/1.1 200 OK
Date: Mon, 09 Nov 2020 19:32:02 GMT
Server: Apache/2.4.29 (Ubuntu)
X-Powered-By: PHP/7.2.30-1+ubuntu18.04.1+deb.sury.org+1
Location: http://127.0.0.1:8080/fcrepo/rest/islandora_3_TECHMD.xml
Cache-Control: no-cache, private
Content-Type: text/html; charset=UTF-8
```
- Now go set `drupal_domain` and `fedora_domain` in your `config.yaml` file.  I used these
```
# Leave these blank unless you know what you're doing.  If you're moving
# data from one server to another and the domain changes, set these
# to your new domain.
fedora_domain: fcrepo.example.org
drupal_domain: drupal.example.org
```
- Do the tests again and confirm the urls are rewritten to use the domains you configured
```
$ curl -s -H "Authorization: Bearer islandora" http://localhost:8000/gemini/02862b7c-0a80-45af-bc2a-690a007e40a0 | jq
{
  "drupal": "http://drupal.example.org/_flysystem/fedora/islandora_3_TECHMD.xml",
  "fedora": "http://fcrepo.example.org/fcrepo/rest/islandora_3_TECHMD.xml"
}
$ curl -I -H "X-Islandora-URI: http://drupal.example.org/_flysystem/fedora/islandora_3_TECHMD.xml" -H "Authorization: Bearer islandora" http://localhost:8000/gemini/by_uri
HTTP/1.1 200 OK
Date: Mon, 09 Nov 2020 19:39:25 GMT
Server: Apache/2.4.29 (Ubuntu)
X-Powered-By: PHP/7.2.30-1+ubuntu18.04.1+deb.sury.org+1
Location: http://fcrepo.example.org/fcrepo/rest/islandora_3_TECHMD.xml
Cache-Control: no-cache, private
Content-Type: text/html; charset=UTF-8
```
- **Change your config back to empty strings or the fedora urls will go missing from your objects' displays**
# Additional Notes:
Part of the ongoin ISLE sprint: https://github.com/orgs/Islandora/projects/2

# Interested parties
@Islandora/8-x-committers

### CODE REVIEW

**Review by seth-shaw-unlv — APPROVED** [review]
Works as advertised. 👍

**Comment by seth-shaw-unlv** [comment]
Other than codecov, it looks good to me, @dannylamb.

**Comment by dannylamb** [comment]
You mind merging @seth-shaw-unlv ?

**Comment by seth-shaw-unlv** [comment]
@dannylamb, are we not worrying about codecov on this one?

**Comment by dannylamb** [comment]
@seth-shaw-unlv Nope, Travis is the only required check that must pass.  Codecov is mostly there to remind us to update the tests, which I did, only to create a 0.15% drop in code coverage :disappointed:

**Comment by dannylamb** [comment]
Many thanks @seth-shaw-unlv :bow:

**Pull request merged**
