### PR TITLE
Add our templates if we did not register the TwigServiceProvider

### PR DESCRIPTION
**Pull request by whikloj**
@DiegoPino @ruebot 

Not sure if we should be executing this in the 
```
if (!isset($app['twig'])) {
```
block as well???

### CODE REVIEW

**Comment by DiegoPino** [comment]
@whikloj not sure. At least in my mind we don't need it inside the `if(!isset(....) {}`, assuming that this whole service really needs `twig` and it's own index.php should provide  a path right?

**Comment by whikloj** [comment]
Ok so, the rule is you include the path in the services during registration [like this](https://github.com/Islandora-CLAW/Crayfish/blob/master/src/app.php#L21-L25) OR you hit this `else` statement if you are registered from a separate service (ala PDX)

**Comment by DiegoPino** [comment]
@ruebot would be nice if you could test this: Ben's gist is a good way, basically GET, POST, DELETE and check if no 50x or 40x appear. First on this directly and then via PDX, but you need also https://github.com/Islandora-CLAW/pdx/pull/4 for the last one

**Comment by whikloj** [comment]
Ok I think this is working, but test it out. I was able to add and delete a resource and create, get and rollback a transaction.

**Pull request merged**
