### PR TITLE
Update Gemini composer for https://github.com/Islandora-Devops/ansibl…

### PR DESCRIPTION
**Pull request by ruebot**
…e-role-crayfish/pull/36

**GitHub Issue**: https://github.com/Islandora-Devops/ansible-role-crayfish/pull/36

# What does this Pull Request do?

Update Gemini composer for composer 2. Follow-on to @alxp's previous PR.

This _should_ take care of the failed build on https://github.com/Islandora-Devops/ansible-role-crayfish/pull/36

# Interested parties
@seth-shaw-unlv @dannylamb

### CODE REVIEW

**Comment by seth-shaw-unlv** [comment]
Travis quickly choked on that one.

**Comment by seth-shaw-unlv** [comment]
Were we using the PSR2 coding standard before? It certainly isn't happy now.

**Comment by seth-shaw-unlv** [comment]
If I can get vagrant and virtualbox to get along I can try to test it later tonight. Just add a comment of what you think the commit message should be, @ruebot,  and we can paste it in when we squash-and-merge.

**Comment by seth-shaw-unlv** [comment]
Despite all my efforts last night, vagrant and virtual box are refusing to let me build a new box. 😡

Someone else may want to swoop in and do this one.

**Comment by elizoller** [comment]
@seth-shaw-unlv i think we need to sort out whats going on with easyrdf first. see https://github.com/Islandora/chullo/pull/91

**Comment by dannylamb** [comment]
Travis is green, let's move this in so we can further diagnose https://github.com/Islandora-Devops/ansible-role-crayfish/pull/36

**Review by dannylamb — APPROVED** [review]

**Pull request merged**
