### PR TITLE
Update .travis.yml

### PR DESCRIPTION
**Pull request by dannylamb**
# What does this Pull Request do?

Travis changes to use scripts at https://github.com/Islandora/islandora_ci

# How should this be tested?

Travis should work

# Interested parties
@rosiel

### CODE REVIEW

**Comment by whikloj** [comment]
Travis is auto-updating to Composer 2.x. 

[`doctrine/migrations`](https://github.com/Islandora/Crayfish/blob/dev/Gemini/composer.json#L7) is updating its dependencies which causes [one error](https://travis-ci.com/github/Islandora/Crayfish/jobs/422260249#L244-L250). That one seems easily fixable, however `symfony/flex` requires a plugin that is only for Composer 1.x which is causing a [second error](https://travis-ci.com/github/Islandora/Crayfish/jobs/422260249#L476-L478). That seems like it would require moving off of `symfony/flex`.

Or you can try forcing composer not to auto-update.

**Comment by dannylamb** [comment]
I just merged https://github.com/Islandora/Crayfish/pull/107 and I'm going to update and try again.

**Comment by dannylamb** [comment]
Yep, that worked.  Many thanks @whikloj and @alxp

**Comment by dannylamb** [comment]
This is good to go @rosiel, or any @Islandora/8-x-committers for that matter

**Comment by seth-shaw-unlv** [comment]
I will note Travis is reporting the following message from tests:
```
1) Islandora\Milliner\Tests\MillinerControllerTest::testMethodsReturnMillinerErrors
Trying to @cover or @use not existing method "\Islandora\Milliner\Controller\MillinerController::createVersion".
```
But that is a separate issue. Let's merge this so Travis is working properly.

**Review by seth-shaw-unlv — APPROVED** [review]
👍

**Pull request merged**
