### PR TITLE
Updating hard coded field names

### PR DESCRIPTION
**Pull request by dannylamb**
**GitHub Issue**: Part of https://github.com/Islandora-CLAW/islandora/pull/86

# What does this Pull Request do?

Updates some checks for field names to include the new media fields from core.

# How should this be tested?

Test as part of https://github.com/Islandora-CLAW/islandora/pull/86

# Interested parties
@Islandora-CLAW/committers @seth-shaw-univ

### CODE REVIEW

**Comment by whikloj** [comment]
I just ran into this with a test migrate. Should we allow a configurable list of fields to look for?

**Comment by seth-shaw-unlv** [comment]
@whikloj, that would make updating this with future media types easier. We should probably push the content model overhaul PRs (including this one) to get it up and working and then create a separate ticket to consider the question afterward.

**Comment by dannylamb** [comment]
After poking around with flysystem stuff I think it's best we pass the source field for a media into crayfish as part of the message.  That's a much nicer way of doing it, and we can pretty easily check if the field is there or empty or w/e.

**Comment by dannylamb** [comment]
@whikloj yup, just about to push it up

**Comment by dannylamb** [comment]
haha, wow, and we've got some weird namespace issues going on, too.  let me touch those up.  hopefully this doesn't spiral.

**Comment by dannylamb** [comment]
...and i need to rebase :1st_place_medal:

**Comment by dannylamb** [comment]
Ok.... so we're green on Travis... BUT:

**Comment by dannylamb** [comment]
@seth-shaw-unlv @whikloj Now Travis is legit green.  Thanks everyone for watching the latest edition of @dannylamb's PR circus
<image src="https://images.gr-assets.com/hostedimages/1393861901ra/8773843.gif" />

**Pull request merged**
