### PR TITLE
Switch Homarus to Symfony 4

### PR DESCRIPTION
**Pull request by whikloj**
**GitHub Issue**: https://github.com/Islandora/documentation/issues/1224

** DO NOT MERGE FIRST **

The sequence for the related PRs is

*  Merge https://github.com/Islandora/Crayfish-Commons/pull/39
*  update Crayfish PR to direct to dev-symfony-flex branch
*  Merge https://github.com/Islandora/Crayfish/pull/102
*  Merge https://github.com/Islandora-Devops/ansible-role-crayfish/pull/34
*  cut a new version of Crayfish role, update islandora-playbook PR
*  Merge https://github.com/Islandora-Devops/islandora-playbook/pull/175

# What does this Pull Request do?

Switches Homarus from Silex to Symfony 4.
Updates Houdini to symfony 4.4

# How should this be tested?

It should work the same as before, no difference when uploading images, audio or video files.

# Interested parties
@Islandora/8-x-committers

### CODE REVIEW

**Comment by elizoller** [comment]
Islandora/Crayfish-Commons#39 has been merged

**Comment by elizoller** [comment]
@whikloj is this one next? or is there a step between?

**Comment by whikloj** [comment]
This one is next, but I need to update the `composer.json` to point back at `dev-symfony-flex` and clean up the merge conflicts. I'll try to do that this week, if not then definitely when I'm back on Tuesday.

**Comment by elizoller** [comment]
great, thanks!

**Comment by whikloj** [comment]
I'm done here, there is some methods with no test coverage so this is not going to pass CodeCov. Specifically the MillinerService method `getFileFromMedia` is not covered. I didn't want to try as I'm out of touch on its function.

**Comment by elizoller** [comment]
@whikloj would the best method for testing be to checkout this branch, do a composer install, and make sure derivatives are still properly made?

**Comment by whikloj** [comment]
@elizoller you can use this branch https://github.com/Islandora-Devops/islandora-playbook/pull/175 to pull in the new Crayfish.

**Comment by whikloj** [comment]
If you want to pull the branch in you can, but you will need to do the configuring which you can see at this PR (https://github.com/Islandora-Devops/ansible-role-crayfish/pull/34) I think

**Comment by elizoller** [comment]
I attempted to spin up a box with the islandora-playbook#175 PR, that didn't work due to composer dependency issues. So I just manually made the changes in that PR over a fresh dev islandora-playbook (so it would use the whikloj branch). Once I had the box up, I verified that Crayfish was checked out to the correct branch. Then I tried to create an object in islandora, but I'm getting 500s from Gemini
```
[Wed Jan 06 16:09:50.423060 2021] [php7:error] [pid 25493] [client 127.0.0.1:47322] PHP Fatal error:  Class Islandora\\Crayfish\\Commons\\Syn\\JwtAuthenticator contains 1 abstract method and must therefore be declared abstract or implement the remaining methods (Symfony\\Component\\Security\\Guard\\AuthenticatorInterface::supports) in /var/www/html/Crayfish/Gemini/vendor/islandora/crayfish-commons/src/Syn/JwtAuthenticator.php on line 16
```

**Comment by whikloj** [comment]
Clearly updating all the composer files for composer 2 was a bad idea. This might be a good time to trash the entire PR and have someone start over.

**Comment by elizoller** [comment]
really? i'd hate to lose all this work!
maybe it would help if danny's PR to remove gemini goes through and then this could rebased over that so it removes at least one component?

**Comment by whikloj** [comment]
The problem is that with all the microservices tied together. This PR never touched Gemini until recently to make Travis pass. So I don't know what is going on with that.

**Comment by whikloj** [comment]
Closed in favour of #133

**Pull request closed without merging**
