### PR TITLE
Add IUuidCache functions for transactions

### PR DESCRIPTION
**Pull request by whikloj**
Addresses https://github.com/Islandora-CLAW/CLAW/issues/185
Depends on https://github.com/Islandora-CLAW/chullo/pull/41

This PR adds the ability to interact with objects inside a transaction. 

CLAW uses a UUID -> Fedora Path mapping which is stored in the triplestore, 
this is generated by fcrepo-camel-toolbox using events coming out of Fedora.

Inside a transaction nothing is permanent until you commit the transaction, therefore no events are generated in the interim so the UUID is not stored in the triplestore.

So we store the temporary path and the UUID in a simple key cache with the transaction ID.

## Testing

Using a turtle file like this
```
@prefix pcdm: <http://pcdm.org/models#> .
@prefix dcterms: <http://purl.org/dc/elements/1.1/> .
@prefix nfo: <http://www.semanticdesktop.org/ontologies/2007/03/22/nfo/v1.2/> .
@prefix xs: <http://www.w3.org/2001/XMLSchema> .

<> a pcdm:Object ;
  dcterms:title "Another PCDM Object" ;
  nfo:uuid "3a28cd77-60ab-498b-aeb4-8292adc2180b"^^xs:string .
```

### Before this PR.
1. Create a resource in Fedora using the /islandora/resource route using the turtle file.
2. Verify you can GET it using the UUID (ie. 3a28cd77-60ab-498b-aeb4-8292adc2180b).
3. Delete it using UUID.
4. Create a transaction.
5. Create a resource in Fedora using the /islandora/resource route using the turtle file inside the transaction.
6. Verify you **CAN'T** GET it using the UUID (ie. 3a28cd77-60ab-498b-aeb4-8292adc2180b).

### After this PR
1. Create a resource in Fedora using the /islandora/resource route using the turtle file.
2. Verify you can GET it using the UUID (ie. 3a28cd77-60ab-498b-aeb4-8292adc2180b).
3. Delete it using UUID.
4. Create a transaction.
5. Create a resource in Fedora using the /islandora/resource route using the turtle file inside the transaction.
6. Verify you **CAN** GET it using the UUID (ie. 3a28cd77-60ab-498b-aeb4-8292adc2180b).
7. Verify you can DELETE the resource using the UUID.

### CODE REVIEW

**Comment by whikloj** [comment]
@ruebot updated with some instructions to test. Let me know if I was unclear or if anything breaks.

**Comment by whikloj** [comment]
Oh I thought we already had `php56-dev` in vagrant, but I might have just edited my local build.

**Comment by DiegoPino** [comment]
@whikloj now you got me thinking. Since thanks to you we have `redis`, what other work can we give `redis` in claw? Maybe a new issue tomorrow

**Comment by whikloj** [comment]
@DiegoPino not sure what we want to use `Redis` for. 

But I wrote it so we could swap it out for a different caching layer, as long as you implement the IUuidCache interface. So it doesn't have to be `Redis`.

**Comment by whikloj** [comment]
Ok I think this is correct now. There were a variety of issues that I did not notice. 

Also I got rid of the UuidServiceProvider as it was duplicating the work in the Chullo UuidGenerator. Then I added it to the CrayfishProvider as I couldn't see why we would keep a second ServiceProvider.

Lastly, I also realized my test turtle file was incorrect. It was missing the hash at the end of the XML Schema prefix.

The file _should_ be
```
@prefix pcdm: <http://pcdm.org/models#> .
@prefix dcterms: <http://purl.org/dc/elements/1.1/> .
@prefix nfo: <http://www.semanticdesktop.org/ontologies/2007/03/22/nfo/v1.2/> .
@prefix xs: <http://www.w3.org/2001/XMLSchema#> .

<> a pcdm:Object ;
  dcterms:title "Another PCDM Object" ;
  nfo:uuid "3a28cd77-60ab-498b-aeb4-8292adc2180b"^^xs:string .
```

My test (with the corrected turtle file) was
```
[/sw/var/www/DAM2/test_objects]
> curl -i -XPOST http://localhost:8282/islandora/transaction
HTTP/1.1 201 Created
Date: Wed, 01 Jun 2016 05:11:38 GMT
Server: Apache/2.4.7 (Ubuntu)
Location: http://localhost:8080/fcrepo/rest/tx:6def4d84-563d-4bc6-8087-917ac03d1aa4
Expires: Wed, 01 Jun 2016 05:14:38 GMT
Cache-Control: private, must-revalidate
Content-Length: 0
Content-Type: text/html; charset=UTF-8

[/sw/var/www/DAM2/test_objects]
> curl -i -XPOST -H"Content-type: text/turtle" --data-binary "@object.ttl" "http://localhost:8282/islandora/resource?tx=tx:6def4d84-563d-4bc6-8087-917ac03d1aa4"
HTTP/1.1 201 Created
Date: Wed, 01 Jun 2016 05:12:39 GMT
Server: Apache/2.4.7 (Ubuntu)
Location: http://localhost:8080/fcrepo/rest/tx:6def4d84-563d-4bc6-8087-917ac03d1aa4/c0/08/5d/10/c0085d10-a7b7-4de1-be81-8cbef5c5e315
Content-Length: 122
Cache-Control: no-cache
Content-Type: text/plain; charset=UTF-8

http://localhost:8080/fcrepo/rest/tx:6def4d84-563d-4bc6-8087-917ac03d1aa4/c0/08/5d/10/c0085d10-a7b7-4de1-be81-8cbef5c5e315

[/sw/var/www/DAM2/test_objects]
> curl -i "http://localhost:8282/islandora/resource/3a28cd77-60ab-498b-aeb4-8292adc2180b?tx=tx:6def4d84-563d-4bc6-8087-917ac03d1aa4"
HTTP/1.1 200 OK
Date: Wed, 01 Jun 2016 05:14:08 GMT
Server: Apache/2.4.7 (Ubuntu)
...
[Removed extra headers and @prefix statements to keep this reasonable]
...
<http://localhost:8080/fcrepo/rest/tx:6def4d84-563d-4bc6-8087-917ac03d1aa4/c0/08/5d/10/c0085d10-a7b7-4de1-be81-8cbef5c5e315> a fedora:Container , fedora:Resource , ns002:Object ;
	dc:title "Another PCDM Object"^^<http://www.w3.org/2001/XMLSchema#string> ;
	ns001:uuid "3a28cd77-60ab-498b-aeb4-8292adc2180b"^^<http://www.w3.org/2001/XMLSchema#string> ;
	a ldp:RDFSource , ldp:Container ;
	fedora:writable "true"^^<http://www.w3.org/2001/XMLSchema#boolean> ;
	fedora:hasParent <http://localhost:8080/fcrepo/rest/tx:6def4d84-563d-4bc6-8087-917ac03d1aa4/> ;
	fedora:numberOfChildren "0"^^<http://www.w3.org/2001/XMLSchema#long> .

<http://localhost:8080/fcrepo/rest/c0/08/5d/10/c0085d10-a7b7-4de1-be81-8cbef5c5e315/fcr:export?format=jcr/xml> dc:format <http://fedora.info/definitions/v4/repository#jcr/xml> .

<http://localhost:8080/fcrepo/rest/tx:6def4d84-563d-4bc6-8087-917ac03d1aa4/c0/08/5d/10/c0085d10-a7b7-4de1-be81-8cbef5c5e315> fedora:exportsAs <http://localhost:8080/fcrepo/rest/c0/08/5d/10/c0085d10-a7b7-4de1-be81-8cbef5c5e315/fcr:export?format=jcr/xml> .

[/sw/var/www/DAM2/test_objects]
> curl -i -XDELETE "http://localhost:8282/islandora/resource/3a28cd77-60ab-498b-aeb4-8292adc2180b?tx=tx:6def4d84-563d-4bc6-8087-917ac03d1aa4" 
HTTP/1.1 204 No Content
Date: Wed, 01 Jun 2016 05:14:19 GMT
Server: Apache/2.4.7 (Ubuntu)
Cache-Control: must-revalidate, private
Content-Length: 0
Content-Type: text/html; charset=UTF-8

[/sw/var/www/DAM2/test_objects]
> curl -i "http://localhost:8282/islandora/resource/3a28cd77-60ab-498b-aeb4-8292adc2180b?tx=tx:6def4d84-563d-4bc6-8087-917ac03d1aa4" 
HTTP/1.1 410 Gone
Date: Wed, 01 Jun 2016 05:14:24 GMT
Server: Apache/2.4.7 (Ubuntu)
Link: <http://localhost:8080/fcrepo/rest/tx:6def4d84-563d-4bc6-8087-917ac03d1aa4/c0/08/5d/10/c0085d10-a7b7-4de1-be81-8cbef5c5e315/fcr:tombstone>; rel="hasTombstone"
Content-Length: 117
Cache-Control: no-cache
Content-Type: text/turtle; charset=UTF-8

Discovered tombstone resource at /c0/08/5d/10/c0085d10-a7b7-4de1-be81-8cbef5c5e315 {jcr:primaryType=fedora:Tombstone}
```

**Comment by DiegoPino** [comment]
@whikloj amazing job 👍 . Working late also! Will give this a look tomorrow. Good night

**Comment by whikloj** [comment]
Thats because you didn't include the transaction ID in your GET. 

You wanted to run
```
curl -i "http://localhost:8282/islandora/resource/3a28cd77-60ab-498b-aeb4-8292adc2180b?tx=tx:bd3e0447-9ea0-419c-b3d6-094817ca0ce0"
```

**Comment by whikloj** [comment]
Did you create a new transaction? 'Cause they expire after 3 minutes of inactivity.

**Comment by whikloj** [comment]
@ruebot I think you are accessing PDX based on the returned header
`X-Powered-By: Islandora Collection REST API v0.0.1`

If so, did you update the composer.json from PDX to use the local Crayfish repository and branch?

My test was run direct against Crayfish, but I can try and re-run it against PDX.

**Comment by whikloj** [comment]
Yeah this is due to an initial failure installing the transforms into Fedora, seems that if it fails once it is dead for all time. I'll have to look into making that more stable.

**Comment by whikloj** [comment]
I'm gonna add a file based cache to this and make that the default. I like Redis and I think it is better, but for setting up vagrant a simple file cache is easier. So I'm looking at https://github.com/beryllium/silex-cache-provider

**Comment by whikloj** [comment]
I just realized that for vagrant we are grabbing the `fcrepo-webapp` and not the `fcrepo-webapp-plus`. Therefore the `fcrepo-transform.jar` is not added and NONE of my transforms will ever work! Must switch to either 

* download the jar and drop it in the fcrepo `WEB-APP/lib` directory 
    
     or
* use the `fcrepo-webapp-plus` which has the dependency built in.

**Comment by whikloj** [comment]
Forget option 1. There are additional (Apache Marmotta) dependencies required, easier to just get the webapp-plus.

**Comment by DiegoPino** [comment]
Are you ok with me merging this? Or do you want to test further?

**Pull request merged**
