### PR TITLE
patched Houdini convert method to add  when making call

### PR DESCRIPTION
**Pull request by dannylamb**
**GitHub Issue**: https://github.com/Islandora/documentation/issues/2165

# What does this Pull Request do?

Tells houdini to only use the first page to generate a derivative.

# What's new?
A slightly modified imagemagick command if you're pulling images from a PDF

# How should this be tested?

Upload a big PDF (50+ MB) and wait a while.  Check the size of the thumbnail/service file that gets generated.  Apply this PR to Crayfish and do it again.  It should be faster and the image should be smaller.

### CODE REVIEW

**Comment by dannylamb** [comment]
Oh codecov, guiltin' me as always.  Hang on.

**Comment by dannylamb** [comment]
I don't understand, I added test coverage codecov!!!!

**Comment by dannylamb** [comment]
Anyhow, I did totally add tests around the branch i introduced for checking if it's a pdf. @Islandora/committers this is good to check out.

**Comment by dannylamb** [comment]
FYI you can test with https://github.com/Islandora-Devops/isle-buildkit/pull/216

**Review by seth-shaw-asu — APPROVED** [review]
This is impressively timely. I was just thinking about this earlier this week. Works as advertised! 👍

**Comment by dannylamb** [comment]
:bow: thanks @seth-shaw-asu !

**Comment by seth-shaw-asu** [comment]
My pleasure. We already have this in production which has resolved some of our problematic thumbnails.

**Pull request merged**
