### PR TITLE
Update symfony/flex.

### PR DESCRIPTION
**Pull request by jordandukart**
**GitHub Issue**: https://github.com/Islandora/documentation/issues/2079

# What does this Pull Request do?

Updates `symfony/flex` that's required due to an end-of-life of their previous download manager.

# What's new?
Version bump.

# How should this be tested?
Houdini should still operate as expected.

# Interested parties
@alxp

### CODE REVIEW

**Comment by alxp** [comment]
Still seem to be getting the same error on composer install and also update:

```bash
vagrant@islandora8:/var/www/html/Crayfish/Houdini$ composer install
Installing dependencies from lock file (including require-dev)
Verifying lock file contents can be installed on current platform.

In PackageFilter.php line 125:
                           
  Undefined index: splits  
                           

install [--prefer-source] [--prefer-dist] [--prefer-install PREFER-INSTALL] [--dry-run] [--dev] [--no-suggest] [--no-dev] [--no-autoloader] [--no-progress] [--no-install] [-v|vv|vvv|--verbose] [-o|--optimize-autoloader] [-a|--classmap-authoritative] [--apcu-autoloader] [--apcu-autoloader-prefix APCU-AUTOLOADER-PREFIX] [--ignore-platform-req IGNORE-PLATFORM-REQ] [--ignore-platform-reqs] [--] [<packages>...]

vagrant@islandora8:/var/www/html/Crayfish/Houdini$ git branch
  2.x
* 2.x-ISLANDORA-2079
  dev
vagrant@islandora8:/var/www/html/Crayfish/Houdini$ 
```

**Comment by alxp** [comment]
The GitHub page referencing this error mentions that symfony/flex  should be at least version 1.17. 

On this PR's branch it's at 1.13.

```bash
$ composer info symfony/flex
name     : symfony/flex
descrip. : Composer plugin for Symfony
keywords : 
versions : * v1.13.3
type     : composer-plugin
license  : MIT License (MIT) (OSI approved) https://spdx.org/licenses/MIT.html#licenseText
homepage : 
source   : [git] https://github.com/symfony/flex.git 2597d0dda8042c43eed44a9cd07236b897e427d7
dist     : [zip] https://api.github.com/repos/symfony/flex/zipball/2597d0dda8042c43eed44a9cd07236b897e427d7 
```

**Comment by jordandukart** [comment]
Thanks for catching @alxp derped on `composer update` versus `composer require`.

**Comment by alxp** [comment]
Updated and tested on fresh Playbook install.

Was able to see Service File mp4, so this update does not seem break Crayfish's functionality.

image

**Review by alxp — APPROVED** [review]

**Pull request merged**
